service: cadastro-paciente

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  # you can overwrite defaults here
  stage: dev
  region: sa-east-1

functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: paciente
          method: get

  obterPaciente:
    handler: handler.obterPaciente
    events:
      - http:
          path: paciente/{pacienteId}
          method: get
